"""
Base Module for CyberEye Security Modules
All detection/utility modules inherit from this
"""

from abc import ABC, abstractmethod
from datetime import datetime
from typing import Dict, Any, Optional, List
import json
import logging

logger = logging.getLogger(__name__)

class SecurityEvent:
    """Security event generated by a module"""
    
    def __init__(self, 
                 module_name: str,
                 event_type: str,
                 severity: str,  # LOW, MEDIUM, HIGH, CRITICAL
                 description: str,
                 data: Dict[str, Any],
                 confidence: float = 0.0):
        self.module_name = module_name
        self.event_type = event_type
        self.severity = severity
        self.description = description
        self.data = data
        self.confidence = confidence
        self.timestamp = datetime.now().isoformat()
        self.event_id = f"{module_name}_{int(datetime.now().timestamp())}"
    
    def to_dict(self) -> Dict:
        return {
            "event_id": self.event_id,
            "module": self.module_name,
            "type": self.event_type,
            "severity": self.severity,
            "description": self.description,
            "data": self.data,
            "confidence": self.confidence,
            "timestamp": self.timestamp
        }

class SecurityModule(ABC):
    """Base class for all security modules"""
    
    def __init__(self, name: str, module_type: str):
        self.name = name
        self.module_type = module_type  # detection, utility, interface
        self.events: List[SecurityEvent] = []
        self.enabled = True
        self.config = {}
        
    @abstractmethod
    def analyze(self, input_data: Any) -> Optional[SecurityEvent]:
        """Main analysis method - to be implemented by each module"""
        pass
    
    @abstractmethod
    def get_capabilities(self) -> Dict[str, Any]:
        """Return what this module can do"""
        pass
    
    def generate_event(self, 
                       event_type: str,
                       severity: str,
                       description: str,
                       data: Dict[str, Any],
                       confidence: float = 0.0) -> SecurityEvent:
        """Helper to create a security event"""
        event = SecurityEvent(
            module_name=self.name,
            event_type=event_type,
            severity=severity,
            description=description,
            data=data,
            confidence=confidence
        )
        self.events.append(event)
        logger.info(f"🔔 {self.name}: {event_type} - {severity}")
        return event
    
    def get_recent_events(self, limit: int = 50) -> List[Dict]:
        """Get recent events from this module"""
        return [e.to_dict() for e in self.events[-limit:]]
    
    def get_stats(self) -> Dict:
        """Get statistics for this module"""
        severity_counts = {"LOW": 0, "MEDIUM": 0, "HIGH": 0, "CRITICAL": 0}
        for event in self.events:
            severity_counts[event.severity] = severity_counts.get(event.severity, 0) + 1
        
        return {
            "name": self.name,
            "type": self.module_type,
            "enabled": self.enabled,
            "total_events": len(self.events),
            "severity_counts": severity_counts,
            "capabilities": self.get_capabilities()
        }